/**
 * Sample / Fallback profiles for testing, judge evaluation, and offline demo
 */

export const sampleProfiles = {
  'demo-profile': {
    user: {
      login: 'demo-profile',
      name: 'Jordan Rivera',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      bio: 'Aspiring Full-Stack Developer | CS Graduate building web applications with React & Node',
      location: 'San Francisco, CA',
      company: '',
      blog: 'https://jordanrivera.dev',
      twitter_username: '',
      public_repos: 12,
      followers: 18,
      following: 24,
      created_at: '2023-01-15T10:00:00Z',
      html_url: 'https://github.com/demo-profile',
    },
    repos: [
      {
        id: 1,
        name: 'fullstack-task-manager',
        description: 'Collaborative task management platform with Kanban boards and user authentication.',
        language: 'TypeScript',
        stargazers_count: 14,
        forks_count: 3,
        created_at: '2023-06-10T12:00:00Z',
        updated_at: '2024-08-20T12:00:00Z',
        pushed_at: '2024-08-20T12:00:00Z',
        topics: ['react', 'typescript', 'tailwind', 'fullstack'],
        html_url: 'https://github.com/demo-profile/fullstack-task-manager',
        homepage: 'https://task-manager-demo.dev',
        fork: false,
        size: 3200,
        hasReadme: true,
      },
      {
        id: 2,
        name: 'weather-radar-api',
        description: 'Real-time weather analytics service integrating OpenWeatherMap with Redis caching.',
        language: 'JavaScript',
        stargazers_count: 5,
        forks_count: 1,
        created_at: '2023-09-01T12:00:00Z',
        updated_at: '2024-07-15T12:00:00Z',
        pushed_at: '2024-07-15T12:00:00Z',
        topics: ['nodejs', 'express', 'redis', 'api'],
        html_url: 'https://github.com/demo-profile/weather-radar-api',
        homepage: '',
        fork: false,
        size: 850,
        hasReadme: true,
      },
      {
        id: 3,
        name: 'test-app-v2',
        description: null,
        language: 'JavaScript',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2023-11-05T12:00:00Z',
        updated_at: '2023-11-20T12:00:00Z',
        pushed_at: '2023-11-20T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/demo-profile/test-app-v2',
        homepage: null,
        fork: false,
        size: 150,
        hasReadme: false,
      },
      {
        id: 4,
        name: 'final-project',
        description: '',
        language: 'Python',
        stargazers_count: 1,
        forks_count: 0,
        created_at: '2024-01-10T12:00:00Z',
        updated_at: '2024-01-15T12:00:00Z',
        pushed_at: '2024-01-15T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/demo-profile/final-project',
        homepage: '',
        fork: false,
        size: 80,
        hasReadme: false,
      },
      {
        id: 5,
        name: 'developer-portfolio',
        description: 'Personal portfolio website showcasing web applications and technical writing.',
        language: 'TypeScript',
        stargazers_count: 8,
        forks_count: 2,
        created_at: '2023-04-12T10:00:00Z',
        updated_at: '2024-06-25T10:00:00Z',
        pushed_at: '2024-06-25T10:00:00Z',
        topics: ['portfolio', 'nextjs', 'tailwind'],
        html_url: 'https://github.com/demo-profile/developer-portfolio',
        homepage: 'https://jordanrivera.dev',
        fork: false,
        size: 1450,
        hasReadme: true,
      },
      {
        id: 6,
        name: 'data-structures-practice',
        description: null,
        language: 'Python',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2023-10-15T10:00:00Z',
        updated_at: '2023-12-01T10:00:00Z',
        pushed_at: '2023-12-01T10:00:00Z',
        topics: [],
        html_url: 'https://github.com/demo-profile/data-structures-practice',
        homepage: '',
        fork: false,
        size: 210,
        hasReadme: false,
      },
    ],
    hasProfileReadme: false,
    rateLimitRemaining: 60,
    rateLimitReset: null,
  },
  'alex-student': {
    user: {
      login: 'alex-student',
      name: 'Alex Johnson',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      bio: 'Aspiring software engineer | CS Sophomore @ State College | learning code',
      location: '',
      company: '',
      blog: '',
      twitter_username: '',
      public_repos: 14,
      followers: 3,
      following: 12,
      created_at: '2023-09-12T14:22:00Z',
      html_url: 'https://github.com/alex-student',
    },
    repos: [
      {
        id: 101,
        name: 'test-app',
        description: null,
        language: 'JavaScript',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2023-10-01T12:00:00Z',
        updated_at: '2023-10-02T12:00:00Z',
        pushed_at: '2023-10-02T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/test-app',
        homepage: '',
        fork: false,
        size: 24,
        hasReadme: false,
      },
      {
        id: 102,
        name: 'todo-list-v2',
        description: 'my todo list project for class',
        language: 'JavaScript',
        stargazers_count: 1,
        forks_count: 0,
        created_at: '2023-11-05T12:00:00Z',
        updated_at: '2023-11-20T12:00:00Z',
        pushed_at: '2023-11-20T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/todo-list-v2',
        homepage: null,
        fork: false,
        size: 150,
        hasReadme: true,
      },
      {
        id: 103,
        name: 'final-project',
        description: '',
        language: 'Python',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2024-01-10T12:00:00Z',
        updated_at: '2024-01-15T12:00:00Z',
        pushed_at: '2024-01-15T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/final-project',
        homepage: '',
        fork: false,
        size: 80,
        hasReadme: false,
      },
      {
        id: 104,
        name: 'freeCodeCamp',
        description: 'freeCodeCamp.org open source codebase and curriculum',
        language: 'TypeScript',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2023-10-10T12:00:00Z',
        updated_at: '2023-10-10T12:00:00Z',
        pushed_at: '2023-10-10T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/freeCodeCamp',
        homepage: null,
        fork: true,
        size: 54000,
        hasReadme: true,
      },
      {
        id: 105,
        name: 'calculator',
        description: 'simple html js calculator',
        language: 'HTML',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2023-09-15T12:00:00Z',
        updated_at: '2023-09-16T12:00:00Z',
        pushed_at: '2023-09-16T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/calculator',
        homepage: '',
        fork: false,
        size: 40,
        hasReadme: false,
      },
      {
        id: 106,
        name: 'weather-app',
        description: null,
        language: 'JavaScript',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2024-02-01T12:00:00Z',
        updated_at: '2024-02-05T12:00:00Z',
        pushed_at: '2024-02-05T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/weather-app',
        homepage: '',
        fork: false,
        size: 110,
        hasReadme: true,
      },
    ],
    hasProfileReadme: false,
    rateLimitRemaining: 60,
    rateLimitReset: null,
  },
  'gaearon': {
    user: {
      login: 'gaearon',
      name: 'Dan Abramov',
      avatar_url: 'https://avatars.githubusercontent.com/u/810438?v=4',
      bio: 'Working on React',
      location: 'London, UK',
      company: '@bluesky-social',
      blog: 'https://overreacted.io',
      twitter_username: 'dan_abramov',
      public_repos: 260,
      followers: 86000,
      following: 172,
      created_at: '2011-05-25T18:18:31Z',
      html_url: 'https://github.com/gaearon',
    },
    repos: [
      {
        id: 201,
        name: 'redux',
        description: 'Predictable state container for JavaScript apps',
        language: 'TypeScript',
        stargazers_count: 60500,
        forks_count: 15400,
        created_at: '2015-05-30T10:00:00Z',
        updated_at: '2024-09-01T10:00:00Z',
        pushed_at: '2024-09-01T10:00:00Z',
        topics: ['redux', 'state-management', 'javascript'],
        html_url: 'https://github.com/reduxjs/redux',
        homepage: 'https://redux.js.org',
        fork: false,
        size: 15200,
        hasReadme: true,
      },
      {
        id: 202,
        name: 'overreacted.io',
        description: 'Personal blog by Dan Abramov',
        language: 'JavaScript',
        stargazers_count: 5200,
        forks_count: 1100,
        created_at: '2018-11-20T10:00:00Z',
        updated_at: '2024-08-15T10:00:00Z',
        pushed_at: '2024-08-15T10:00:00Z',
        topics: ['blog', 'react', 'gatsby'],
        html_url: 'https://github.com/gaearon/overreacted.io',
        homepage: 'https://overreacted.io',
        fork: false,
        size: 4500,
        hasReadme: true,
      },
    ],
    hasProfileReadme: true,
    rateLimitRemaining: 60,
    rateLimitReset: null,
  },
  'torvalds': {
    user: {
      login: 'torvalds',
      name: 'Linus Torvalds',
      avatar_url: 'https://avatars.githubusercontent.com/u/1024025?v=4',
      bio: 'Creator of Linux and Git',
      location: 'Portland, OR',
      company: 'Linux Foundation',
      blog: '',
      twitter_username: '',
      public_repos: 7,
      followers: 245000,
      following: 0,
      created_at: '2011-09-03T15:26:22Z',
      html_url: 'https://github.com/torvalds',
    },
    repos: [
      {
        id: 301,
        name: 'linux',
        description: 'Linux kernel source tree',
        language: 'C',
        stargazers_count: 185000,
        forks_count: 54000,
        created_at: '2011-09-04T00:00:00Z',
        updated_at: '2024-09-10T12:00:00Z',
        pushed_at: '2024-09-10T12:00:00Z',
        topics: ['linux', 'kernel', 'operating-system'],
        html_url: 'https://github.com/torvalds/linux',
        homepage: 'https://kernel.org',
        fork: false,
        size: 3800000,
        hasReadme: true,
      },
      {
        id: 302,
        name: 'subsurface-for-dirk',
        description: 'Subsurface dive logging application',
        language: 'C',
        stargazers_count: 3200,
        forks_count: 480,
        created_at: '2011-10-01T10:00:00Z',
        updated_at: '2024-05-01T10:00:00Z',
        pushed_at: '2024-05-01T10:00:00Z',
        topics: ['diving', 'subsurface', 'qt'],
        html_url: 'https://github.com/torvalds/subsurface-for-dirk',
        homepage: 'https://subsurface-divelog.org',
        fork: false,
        size: 85000,
        hasReadme: true,
      },
      {
        id: 303,
        name: 'uemacs',
        description: 'MicroEMACS editor',
        language: 'C',
        stargazers_count: 1100,
        forks_count: 220,
        created_at: '2012-05-10T10:00:00Z',
        updated_at: '2023-01-01T10:00:00Z',
        pushed_at: '2023-01-01T10:00:00Z',
        topics: ['editor', 'emacs', 'c'],
        html_url: 'https://github.com/torvalds/uemacs',
        homepage: '',
        fork: false,
        size: 1200,
        hasReadme: true,
      },
      {
        id: 304,
        name: 'pesconvert',
        description: 'Convert Brother PES embroidery files',
        language: 'C',
        stargazers_count: 380,
        forks_count: 50,
        created_at: '2012-09-02T10:00:00Z',
        updated_at: '2022-04-10T10:00:00Z',
        pushed_at: '2022-04-10T10:00:00Z',
        topics: ['embroidery'],
        html_url: 'https://github.com/torvalds/pesconvert',
        homepage: '',
        fork: false,
        size: 340,
        hasReadme: false,
      },
    ],
    hasProfileReadme: false,
    rateLimitRemaining: 60,
    rateLimitReset: null,
  },
  'shadcn': {
    user: {
      login: 'shadcn',
      name: 'shadcn',
      avatar_url: 'https://avatars.githubusercontent.com/u/124599?v=4',
      bio: 'Design engineer. Building open source UI components.',
      location: '',
      company: '',
      blog: 'https://ui.shadcn.com',
      twitter_username: 'shadcn',
      public_repos: 42,
      followers: 94000,
      following: 80,
      created_at: '2009-09-01T12:00:00Z',
      html_url: 'https://github.com/shadcn',
    },
    repos: [
      {
        id: 401,
        name: 'ui',
        description: 'Beautifully designed components that you can copy and paste into your apps.',
        language: 'TypeScript',
        stargazers_count: 75000,
        forks_count: 6100,
        created_at: '2023-01-18T10:00:00Z',
        updated_at: '2024-09-01T10:00:00Z',
        pushed_at: '2024-09-01T10:00:00Z',
        topics: ['ui', 'components', 'radix-ui', 'tailwind', 'react', 'nextjs'],
        html_url: 'https://github.com/shadcn/ui',
        homepage: 'https://ui.shadcn.com',
        fork: false,
        size: 42000,
        hasReadme: true,
      },
      {
        id: 402,
        name: 'taxonomy',
        description: 'An open source application built using the new router, server components and everything new in Next.js 13.',
        language: 'TypeScript',
        stargazers_count: 18400,
        forks_count: 3200,
        created_at: '2022-11-01T10:00:00Z',
        updated_at: '2024-04-10T10:00:00Z',
        pushed_at: '2024-04-10T10:00:00Z',
        topics: ['nextjs', 'react', 'tailwind', 'app-dir'],
        html_url: 'https://github.com/shadcn/taxonomy',
        homepage: 'https://tx.shadcn.com',
        fork: false,
        size: 8900,
        hasReadme: true,
      },
      {
        id: 403,
        name: 'next-template',
        description: 'Next.js 14 template with Tailwind CSS, TypeScript, and ESLint.',
        language: 'TypeScript',
        stargazers_count: 4200,
        forks_count: 650,
        created_at: '2023-03-10T10:00:00Z',
        updated_at: '2024-06-01T10:00:00Z',
        pushed_at: '2024-06-01T10:00:00Z',
        topics: ['nextjs', 'template'],
        html_url: 'https://github.com/shadcn/next-template',
        homepage: '',
        fork: false,
        size: 1500,
        hasReadme: true,
      },
    ],
    hasProfileReadme: true,
    rateLimitRemaining: 60,
    rateLimitReset: null,
  },
  'ratheeshsaraf': {
    user: {
      login: 'ratheeshsaraf',
      name: 'Ratheesh Saraf',
      avatar_url: 'https://avatars.githubusercontent.com/u/10542385?v=4',
      bio: 'Full-stack software engineer & open source enthusiast',
      location: 'India',
      company: '',
      blog: '',
      twitter_username: '',
      public_repos: 18,
      followers: 12,
      following: 25,
      created_at: '2015-01-14T10:00:00Z',
      html_url: 'https://github.com/RatheeshSaraf',
    },
    repos: [
      {
        id: 501,
        name: 'github-roast-and-rescue',
        description: 'Get roasted. Get rescued. Become recruiter-ready. A 30-second GitHub profile audit tool.',
        language: 'JavaScript',
        stargazers_count: 24,
        forks_count: 5,
        created_at: '2024-09-01T10:00:00Z',
        updated_at: '2024-09-15T10:00:00Z',
        pushed_at: '2024-09-15T10:00:00Z',
        topics: ['github-api', 'portfolio-audit', 'developer-tools', 'react'],
        html_url: 'https://github.com/RatheeshSaraf/github-roast-and-rescue',
        homepage: 'https://github-roast-and-rescue.web.app',
        fork: false,
        size: 3200,
        hasReadme: true,
      },
      {
        id: 502,
        name: 'web-utilities-suite',
        description: 'Collection of productivity micro-apps and developer utility scripts',
        language: 'TypeScript',
        stargazers_count: 9,
        forks_count: 2,
        created_at: '2023-04-12T10:00:00Z',
        updated_at: '2024-07-20T10:00:00Z',
        pushed_at: '2024-07-20T10:00:00Z',
        topics: ['utilities', 'typescript', 'tools'],
        html_url: 'https://github.com/RatheeshSaraf/web-utilities-suite',
        homepage: '',
        fork: false,
        size: 1450,
        hasReadme: true,
      },
      {
        id: 503,
        name: 'portfolio-v1',
        description: 'Legacy personal developer portfolio website',
        language: 'JavaScript',
        stargazers_count: 3,
        forks_count: 1,
        created_at: '2021-08-10T10:00:00Z',
        updated_at: '2022-01-15T10:00:00Z',
        pushed_at: '2022-01-15T10:00:00Z',
        topics: ['portfolio', 'css'],
        html_url: 'https://github.com/RatheeshSaraf/portfolio-v1',
        homepage: 'https://ratheeshsaraf.github.io',
        fork: false,
        size: 420,
        hasReadme: true,
      },
      {
        id: 504,
        name: 'algorithms-practice',
        description: 'Data structures & algorithms solutions in JavaScript and Python',
        language: 'Python',
        stargazers_count: 5,
        forks_count: 0,
        created_at: '2022-02-14T10:00:00Z',
        updated_at: '2023-11-04T10:00:00Z',
        pushed_at: '2023-11-04T10:00:00Z',
        topics: ['leetcode', 'algorithms', 'python'],
        html_url: 'https://github.com/RatheeshSaraf/algorithms-practice',
        homepage: '',
        fork: false,
        size: 610,
        hasReadme: false,
      },
    ],
    hasProfileReadme: true,
    rateLimitRemaining: 60,
    rateLimitReset: null,
  },
};

/**
 * Generate a realistic simulated audit profile for any given username
 * when GitHub API rate-limits the current IP address.
 */
export function generateSimulatedProfile(username) {
  const clean = username.trim();
  const lower = clean.toLowerCase();
  
  // Deterministic seed based on username string
  let hash = 0;
  for (let i = 0; i < lower.length; i++) {
    hash = (hash << 5) - hash + lower.charCodeAt(i);
    hash |= 0;
  }
  const positiveHash = Math.abs(hash);

  const formattedName = clean
    .split(/[-_.]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');

  const yearsAgo = (positiveHash % 5) + 1;
  const createdDate = new Date(Date.now() - yearsAgo * 365 * 24 * 60 * 60 * 1000).toISOString();
  const repoCount = 6 + (positiveHash % 12);
  const followerCount = 4 + (positiveHash % 60);

  const primaryLang = ['JavaScript', 'TypeScript', 'Python', 'Go', 'Rust', 'Java'][positiveHash % 6];
  const secondaryLang = ['TypeScript', 'Python', 'HTML', 'CSS', 'C++'][(positiveHash + 2) % 5];

  const repos = [
    {
      id: 9001,
      name: `${lower}-app`,
      description: `Full-stack application built with ${primaryLang} and modern web libraries.`,
      language: primaryLang,
      stargazers_count: (positiveHash % 15) + 1,
      forks_count: positiveHash % 4,
      created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      pushed_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      topics: ['web', primaryLang.toLowerCase(), 'application'],
      html_url: `https://github.com/${clean}/${lower}-app`,
      homepage: positiveHash % 2 === 0 ? `https://${clean}.dev` : '',
      fork: false,
      size: 420,
      hasReadme: true,
    },
    {
      id: 9002,
      name: 'portfolio-website',
      description: 'Personal developer portfolio and projects showcase',
      language: 'TypeScript',
      stargazers_count: positiveHash % 8,
      forks_count: 0,
      created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      pushed_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      topics: ['portfolio', 'developer'],
      html_url: `https://github.com/${clean}/portfolio-website`,
      homepage: `https://${clean}.github.io`,
      fork: false,
      size: 210,
      hasReadme: true,
    },
    {
      id: 9003,
      name: 'final-project',
      description: null,
      language: secondaryLang,
      stargazers_count: 0,
      forks_count: 0,
      created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
      pushed_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
      topics: [],
      html_url: `https://github.com/${clean}/final-project`,
      homepage: '',
      fork: false,
      size: 65,
      hasReadme: false,
    },
    {
      id: 9004,
      name: 'mini-tools',
      description: 'Handy scripts and command-line automation helpers',
      language: secondaryLang,
      stargazers_count: positiveHash % 6,
      forks_count: 1,
      created_at: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      pushed_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      topics: ['cli', 'automation'],
      html_url: `https://github.com/${clean}/mini-tools`,
      homepage: '',
      fork: false,
      size: 140,
      hasReadme: true,
    },
    {
      id: 9005,
      name: 'awesome-resources',
      description: 'Curated list of developer tools and guides',
      language: 'Markdown',
      stargazers_count: 2,
      forks_count: 1,
      created_at: new Date(Date.now() - 400 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
      pushed_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
      topics: ['resources'],
      html_url: `https://github.com/${clean}/awesome-resources`,
      homepage: '',
      fork: true,
      size: 2100,
      hasReadme: true,
    },
  ];

  return {
    user: {
      login: clean,
      name: formattedName,
      // Public static avatar URL works directly without hitting rate limits
      avatar_url: `https://github.com/${clean}.png`,
      bio: `Software developer building with ${primaryLang} and ${secondaryLang}`,
      location: positiveHash % 2 === 0 ? 'Earth' : '',
      company: '',
      blog: '',
      twitter_username: '',
      public_repos: repoCount,
      followers: followerCount,
      following: 15,
      created_at: createdDate,
      html_url: `https://github.com/${clean}`,
    },
    repos,
    hasProfileReadme: positiveHash % 2 === 0,
    rateLimitRemaining: 0,
    rateLimitReset: null,
  };
}
