/**
 * Sample / Fallback profiles for testing, judge evaluation, and offline demo
 */

export const sampleProfiles = {
  'alex-student': {
    user: {
      login: 'alex-student',
      name: 'Alex Johnson',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      bio: 'Aspiring software engineer | CS Sophomore @ State College | learning code',
      location: '',
      company: '',
      blog: '',
      twitter_username: '',
      public_repos: 14,
      followers: 3,
      following: 12,
      created_at: '2023-09-12T14:22:00Z',
      html_url: 'https://github.com/alex-student',
    },
    repos: [
      {
        id: 101,
        name: 'test-app',
        description: null,
        language: 'JavaScript',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2023-10-01T12:00:00Z',
        updated_at: '2023-10-02T12:00:00Z',
        pushed_at: '2023-10-02T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/test-app',
        homepage: '',
        fork: false,
        size: 24,
        hasReadme: false,
      },
      {
        id: 102,
        name: 'todo-list-v2',
        description: 'my todo list project for class',
        language: 'JavaScript',
        stargazers_count: 1,
        forks_count: 0,
        created_at: '2023-11-05T12:00:00Z',
        updated_at: '2023-11-20T12:00:00Z',
        pushed_at: '2023-11-20T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/todo-list-v2',
        homepage: null,
        fork: false,
        size: 150,
        hasReadme: true,
      },
      {
        id: 103,
        name: 'final-project',
        description: '',
        language: 'Python',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2024-01-10T12:00:00Z',
        updated_at: '2024-01-15T12:00:00Z',
        pushed_at: '2024-01-15T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/final-project',
        homepage: '',
        fork: false,
        size: 80,
        hasReadme: false,
      },
      {
        id: 104,
        name: 'freeCodeCamp',
        description: 'freeCodeCamp.org open source codebase and curriculum',
        language: 'TypeScript',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2023-10-10T12:00:00Z',
        updated_at: '2023-10-10T12:00:00Z',
        pushed_at: '2023-10-10T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/freeCodeCamp',
        homepage: null,
        fork: true,
        size: 54000,
        hasReadme: true,
      },
      {
        id: 105,
        name: 'calculator',
        description: 'simple html js calculator',
        language: 'HTML',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2023-09-15T12:00:00Z',
        updated_at: '2023-09-16T12:00:00Z',
        pushed_at: '2023-09-16T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/calculator',
        homepage: '',
        fork: false,
        size: 40,
        hasReadme: false,
      },
      {
        id: 106,
        name: 'weather-app',
        description: null,
        language: 'JavaScript',
        stargazers_count: 0,
        forks_count: 0,
        created_at: '2024-02-01T12:00:00Z',
        updated_at: '2024-02-05T12:00:00Z',
        pushed_at: '2024-02-05T12:00:00Z',
        topics: [],
        html_url: 'https://github.com/alex-student/weather-app',
        homepage: '',
        fork: false,
        size: 110,
        hasReadme: true,
      },
    ],
    hasProfileReadme: false,
    rateLimitRemaining: 60,
    rateLimitReset: null,
  },
  'gaearon': {
    user: {
      login: 'gaearon',
      name: 'Dan Abramov',
      avatar_url: 'https://avatars.githubusercontent.com/u/810438?v=4',
      bio: 'Working on React',
      location: 'London, UK',
      company: '@bluesky-social',
      blog: 'https://overreacted.io',
      twitter_username: 'dan_abramov',
      public_repos: 260,
      followers: 86000,
      following: 172,
      created_at: '2011-05-25T18:18:31Z',
      html_url: 'https://github.com/gaearon',
    },
    repos: [
      {
        id: 201,
        name: 'redux',
        description: 'Predictable state container for JavaScript apps',
        language: 'TypeScript',
        stargazers_count: 60500,
        forks_count: 15400,
        created_at: '2015-05-30T10:00:00Z',
        updated_at: '2024-09-01T10:00:00Z',
        pushed_at: '2024-09-01T10:00:00Z',
        topics: ['redux', 'state-management', 'javascript'],
        html_url: 'https://github.com/reduxjs/redux',
        homepage: 'https://redux.js.org',
        fork: false,
        size: 15200,
        hasReadme: true,
      },
      {
        id: 202,
        name: 'overreacted.io',
        description: 'Personal blog by Dan Abramov',
        language: 'JavaScript',
        stargazers_count: 5200,
        forks_count: 1100,
        created_at: '2018-11-20T10:00:00Z',
        updated_at: '2024-08-15T10:00:00Z',
        pushed_at: '2024-08-15T10:00:00Z',
        topics: ['blog', 'react', 'gatsby'],
        html_url: 'https://github.com/gaearon/overreacted.io',
        homepage: 'https://overreacted.io',
        fork: false,
        size: 4500,
        hasReadme: true,
      },
    ],
    hasProfileReadme: true,
    rateLimitRemaining: 60,
    rateLimitReset: null,
  },
};
